# Generated by Django 2.2.6 on 2020-09-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, null=True, verbose_name='Название События')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('translation', models.URLField(null=True, verbose_name='Трансляция')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата и время проведения')),
                ('draft', models.BooleanField(blank=True, null=True, verbose_name='добавить в архив')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Название организации')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('logo', models.ImageField(null=True, upload_to='Company/logo', verbose_name='Логотип компании')),
                ('site', models.URLField(verbose_name='Сайт компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField(verbose_name='Награждение')),
                ('company', models.ManyToManyField(to='Event.Organisation', verbose_name='Победитель')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.Event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Призер',
                'verbose_name_plural': 'Призеры',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.ManyToManyField(to='Event.Organisation', verbose_name='Учаcтники'),
        ),
    ]
