# Generated by Django 2.2.6 on 2020-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название победителя')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Призер',
                'verbose_name_plural': 'Призеры',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='Event.Video', verbose_name='Призеры'),
        ),
    ]
