# Generated by Django 3.1.4 on 2021-01-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20200921_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Поздравление', 'verbose_name_plural': 'Поздравления'},
        ),
    ]
