# Generated by Django 3.1.5 on 2021-03-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('text', models.TextField(default='', null=True, verbose_name='Описание раздела')),
                ('slug', models.SlugField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Название')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя файла')),
                ('file', models.FileField(max_length=100000000, null=True, upload_to='Documents')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.subsection', verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
