# Generated by Django 3.1.5 on 2021-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_subsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст'),
        ),
    ]
