# Generated by Django 3.0.2 on 2020-01-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
