# Generated by Django 3.0.2 on 2020-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0002_auto_20200128_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
    ]
