# Generated by Django 3.1.5 on 2021-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0002_contacttranslate_contacttranslatetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='territory',
            field=models.CharField(choices=[('oez', 'ОЭЗ ППТ'), ('oezru', 'ОЭЗ Ру'), ('industrial', 'Индустриальный парк'), ('techno', 'Технопарк'), ('any', 'Иная площадка')], max_length=50, verbose_name='Территория участка'),
        ),
        migrations.AlterField(
            model_name='greenfieldtranslatetranslation',
            name='territory',
            field=models.CharField(choices=[('oez', 'ОЭЗ ППТ'), ('oezru', 'ОЭЗ Ру'), ('industrial', 'Индустриальный парк'), ('techno', 'Технопарк'), ('any', 'Иная площадка')], max_length=50, null=True, verbose_name='Территория участка'),
        ),
    ]
