# Generated by Django 3.1.5 on 2021-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0003_auto_20210313_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Рассмотрено'),
        ),
    ]
