# Generated by Django 3.0.2 on 2020-01-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0004_connect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.RemoveField(
            model_name='connect',
            name='created',
        ),
    ]
