# Generated by Django 3.0.2 on 2020-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0005_auto_20200131_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата обращения'),
        ),
    ]
