# Generated by Django 3.0.2 on 2020-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0009_auto_20200210_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='static/news/img'),
        ),
    ]
