# Generated by Django 3.0.2 on 2020-02-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0012_auto_20200210_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Кадастровый номер')),
                ('image', models.ImageField(null=True, upload_to='greenfield')),
                ('square', models.CharField(max_length=10, verbose_name='Площадь(га)')),
                ('form', models.CharField(choices=[('goverment', 'государственная'), ('private', 'частная')], max_length=30, verbose_name='Форма собственности')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_api.Region')),
            ],
            options={
                'verbose_name': 'Гринфилд',
                'ordering': ('number',),
            },
        ),
    ]
