# Generated by Django 3.0.2 on 2020-02-21 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0013_greenfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Создан'),
        ),
    ]
