# Generated by Django 2.2.6 on 2020-03-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0014_auto_20200221_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brownfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Кадастровый номер')),
                ('image', models.ImageField(null=True, upload_to='brownfield')),
                ('square', models.CharField(max_length=15, verbose_name='Площадь(га)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_api.Region')),
            ],
            options={
                'verbose_name': 'Браунфилд',
                'ordering': ('number',),
            },
        ),
    ]
