# Generated by Django 2.2.6 on 2020-03-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0016_straight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отрасли')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.DeleteModel(
            name='Straight',
        ),
    ]
