# Generated by Django 2.2.6 on 2020-03-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0017_auto_20200317_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=150, verbose_name='Получатель')),
                ('name', models.CharField(max_length=500, verbose_name='Имя поддержки')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('type', models.CharField(choices=[('grant', 'грант'), ('direct', 'Прямая финансовая поддержка'), ('loan', 'заемное финансирование')], max_length=50, verbose_name='Тип поддержки')),
                ('organisation', models.TextField(verbose_name='кто выдает меру поддержки')),
                ('category', models.CharField(blank=True, max_length=70, verbose_name='Категория налогоплатильщика')),
                ('property_rate', models.TextField(blank=True, verbose_name='Налоговая ставка на имущество')),
                ('profit', models.TextField(blank=True, verbose_name='Налог на прибыль')),
                ('transport', models.TextField(blank=True, verbose_name='Налоговая ставка по транспортному налогу')),
                ('land', models.TextField(blank=True, verbose_name='Налоговая ставка по земельному налогу')),
                ('nds', models.TextField(blank=True, verbose_name='Налоговая ставка НДС')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_api.Industry', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Мера поддержки',
                'verbose_name_plural': 'Меры поддержки',
            },
        ),
    ]
