# Generated by Django 2.2.6 on 2020-03-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0018_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='expenses',
            field=models.TextField(blank=True, verbose_name='Затраты подлежащие возмещению'),
        ),
    ]
