# Generated by Django 2.2.6 on 2020-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0019_support_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
    ]
