# Generated by Django 2.2.6 on 2020-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0020_connect_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='condition',
            field=models.TextField(blank=True, verbose_name='Условия'),
        ),
    ]
