# Generated by Django 2.2.6 on 2020-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0021_support_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='recipient',
            field=models.CharField(choices=[('msp', 'МСП'), ('other', 'Другие')], max_length=150, verbose_name='Получатель'),
        ),
    ]
