# Generated by Django 2.2.6 on 2020-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0022_auto_20200317_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='body',
        ),
        migrations.AlterField(
            model_name='support',
            name='recipient',
            field=models.CharField(choices=[('small', 'МСП'), ('big', 'Крупное предпринимательство')], max_length=150, verbose_name='Получатель'),
        ),
    ]
