# Generated by Django 2.2.6 on 2020-03-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0023_auto_20200317_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
