# Generated by Django 2.2.6 on 2020-03-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0026_auto_20200317_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
