# Generated by Django 2.2.6 on 2020-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0027_delete_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(blank=True, choices=[('oez', 'ОЭЗ'), ('park', 'индустриальный парк'), ('mono', 'моногород'), ('vne', 'территория вне'), ('all', 'любая')], max_length=50, verbose_name='Территория реализации проекта')),
                ('recipient', models.CharField(choices=[('small', 'Малый (1-100 чел.)'), ('medium', 'Средний (100-250 чел.)'), ('small_medium', 'Малый и средний (1-250 чел.)'), ('big', 'Крупный (от 251 чел.)'), ('all', 'Все')], max_length=150, verbose_name='Получатель')),
                ('name', models.CharField(max_length=500, verbose_name='Имя поддержки')),
                ('condition', models.TextField(blank=True, verbose_name='Условия')),
                ('type', models.CharField(choices=[('direct', 'Прямая финансовая поддержка'), ('loan', 'заемное финансирование')], max_length=50, verbose_name='Тип поддержки')),
                ('organisation', models.TextField(verbose_name='кто выдает меру поддержки')),
                ('category', models.CharField(blank=True, max_length=70, verbose_name='Категория налогоплатильщика')),
                ('property_rate', models.TextField(blank=True, verbose_name='Налоговая ставка на имущество')),
                ('profit', models.TextField(blank=True, verbose_name='Налог на прибыль')),
                ('transport', models.TextField(blank=True, verbose_name='Налоговая ставка по транспортному налогу')),
                ('land', models.TextField(blank=True, verbose_name='Налоговая ставка по земельному налогу')),
                ('nds', models.TextField(blank=True, verbose_name='Налоговая ставка НДС')),
                ('expenses', models.TextField(blank=True, verbose_name='Затраты подлежащие возмещению')),
                ('industry', models.ManyToManyField(to='example_api.Industry', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Мера поддержки',
                'verbose_name_plural': 'Меры поддержки',
            },
        ),
    ]
