# Generated by Django 2.2.6 on 2020-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0028_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='type',
            field=models.CharField(choices=[('greenfield', 'Гринфилд'), ('brownfield', 'Браунфилд')], default=0, max_length=20, verbose_name='Тип участка'),
        ),
        migrations.DeleteModel(
            name='Brownfield',
        ),
    ]
