# Generated by Django 2.2.6 on 2020-03-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0029_auto_20200320_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenfield',
            options={'ordering': ('number',), 'verbose_name': 'Земельный участок', 'verbose_name_plural': 'Земельные участки'},
        ),
    ]
