# Generated by Django 2.2.6 on 2020-03-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0031_support_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='form',
        ),
    ]
