# Generated by Django 2.2.6 on 2020-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0032_remove_support_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='form',
            field=models.CharField(choices=[('lawyer', 'Юр.лицо'), ('ip', 'ИП')], default=0, max_length=20, verbose_name='Категория получателя'),
        ),
    ]
