# Generated by Django 2.2.6 on 2020-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0033_support_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='summ',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сумма займа'),
        ),
        migrations.AlterField(
            model_name='support',
            name='category',
            field=models.CharField(blank=True, max_length=300, verbose_name='Категория налогоплатильщика'),
        ),
        migrations.AlterField(
            model_name='support',
            name='form',
            field=models.CharField(blank=True, choices=[('lawyer', 'Юр.лицо'), ('ip', 'ИП')], default=0, max_length=20, verbose_name='Категория получателя'),
        ),
    ]
