# Generated by Django 2.2.6 on 2020-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0034_auto_20200320_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='authority',
            field=models.CharField(blank=True, choices=[('uilo', 'УИиИ ЛО'), ('min', 'Минпромторг России'), ('bank', 'Уполномоченные банки'), ('fond', 'Фонд содействия инновациям'), ('rvk', 'АО "РВК"'), ('business', 'Центры "мой бизнес", Управляющие компании')], max_length=50, verbose_name='Куррирующий орган'),
        ),
        migrations.AddField(
            model_name='support',
            name='implementation',
            field=models.CharField(blank=True, choices=[('agreement', 'Соглашение'), ('gchp', 'ГЧП'), ('any', 'Любой')], max_length=50, verbose_name='Способ реализации проекта'),
        ),
        migrations.AddField(
            model_name='support',
            name='target',
            field=models.TextField(default=0, verbose_name='Цели/адресаты гос.поддержки'),
        ),
        migrations.AddField(
            model_name='support',
            name='type_project',
            field=models.CharField(blank=True, choices=[('new', 'Новое строительство'), ('reconstuction', 'Реконструкция'), ('modernisation', 'Модернизация')], max_length=50, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='form',
            field=models.CharField(choices=[('direct', 'инвестиции'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии')], max_length=30, verbose_name='Форма собственности'),
        ),
        migrations.AlterField(
            model_name='support',
            name='form',
            field=models.CharField(blank=True, choices=[('lawyer', 'Юр.лицо'), ('ip', 'ИП'), ('municipality', 'Муниципалитет')], default=0, max_length=20, verbose_name='Категория получателя'),
        ),
        migrations.AlterField(
            model_name='support',
            name='recipient',
            field=models.CharField(choices=[('small', 'МСП'), ('innovation', 'Инновации'), ('all', 'Все'), ('municipality', 'муниципалитет'), ('industrial', 'Резиденты индустриальных парков'), ('developers', 'Разработчики ПО'), ('resident_oez', 'Резиденты ОЭЗРУ Липецк'), ('subject', 'Субъект'), ('legally', 'Юридические лица'), ('cooperatives', 'Кооперативы'), ('all', 'Все кроме МСП')], max_length=150, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='support',
            name='territory',
            field=models.CharField(blank=True, choices=[('without', 'Без ограничений'), ('park', 'индустриальные парки'), ('mono', 'моногород'), ('techno', 'технопарк'), ('oez', 'ОЭЗ ппт липецк'), ('oezru', 'ОЭЗРУ'), ('cluster', 'Участник кластера'), ('all', 'Любая')], max_length=50, verbose_name='Территория реализации проекта'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('direct', 'инвестиции'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии')], max_length=50, verbose_name='Тип поддержки'),
        ),
    ]
