# Generated by Django 2.2.6 on 2020-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0035_auto_20200323_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='money',
            field=models.CharField(blank=True, max_length=150, verbose_name='Объем меры гос.поддержки(млрд.руб.)'),
        ),
        migrations.AddField(
            model_name='support',
            name='npa',
            field=models.TextField(blank=True, default=0, verbose_name='НПА устанавливающий меры'),
        ),
        migrations.AddField(
            model_name='support',
            name='program_name',
            field=models.TextField(default=0, verbose_name='Наименование гос.программы'),
        ),
        migrations.AddField(
            model_name='support',
            name='project_name',
            field=models.TextField(blank=True, default=0, verbose_name='Наименование национального проекта'),
        ),
        migrations.AlterField(
            model_name='support',
            name='target',
            field=models.TextField(blank=True, default=0, verbose_name='Цели/адресаты гос.поддержки'),
        ),
    ]
