# Generated by Django 3.0.1 on 2020-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0036_auto_20200323_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='form',
            field=models.CharField(choices=[('direct', 'инвестиции'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=30, verbose_name='Форма собственности'),
        ),
        migrations.AlterField(
            model_name='support',
            name='recipient',
            field=models.CharField(choices=[('small', 'МСП'), ('innovation', 'Инновации'), ('all', 'Все'), ('municipality', 'муниципалитет'), ('industrial', 'Резиденты индустриальных парков'), ('developers', 'Разработчики ПО'), ('resident_oez', 'Резиденты ОЭЗРУ Липецк'), ('subject', 'Субъект'), ('legally', 'Юридические лица'), ('cooperatives', 'Кооперативы'), ('not_msp', 'Все кроме МСП')], max_length=150, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('direct', 'инвестиции'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=50, verbose_name='Тип поддержки'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type_project',
            field=models.CharField(blank=True, choices=[('new', 'Новое строительство'), ('reconstuction', 'Реконструкция'), ('modernisation', 'Модернизация'), ('all', 'любой')], max_length=50, verbose_name='Тип проекта'),
        ),
    ]
