# Generated by Django 2.2.6 on 2020-04-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0038_auto_20200428_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='gas',
            field=models.CharField(blank=True, max_length=20, verbose_name='Газоснабжение'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='heat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Теплоснабжение'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='power',
            field=models.CharField(blank=True, max_length=20, verbose_name='Электроснабжение'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='water',
            field=models.CharField(blank=True, max_length=20, verbose_name='Водоснабжение'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='water_out',
            field=models.CharField(blank=True, max_length=20, verbose_name='Теплоотведение'),
        ),
        migrations.DeleteModel(
            name='InformationForRegion',
        ),
    ]
