# Generated by Django 2.2.6 on 2020-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0039_auto_20200428_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание участка'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='privileges',
            field=models.TextField(blank=True, verbose_name='Льготы'),
        ),
    ]
