# Generated by Django 2.2.6 on 2020-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0040_auto_20200428_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='danger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=500, verbose_name='Класс опасности'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание участка'),
        ),
    ]
