# Generated by Django 2.2.6 on 2020-04-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0041_auto_20200428_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='category',
            field=models.CharField(choices=[('0', 'Земли сельского назначения'), ('1', 'земли населенных пунктов'), ('2', 'земли промышленности, энергетики, транспорта, связи, радиовещания, телевидения, информатики, земли для обеспечения космической деятельности, земли обороны, безопасности и земли иного специального назначения'), ('3', 'земли особо охраняемых территорий и объектов'), ('4', 'земли лесного фонда'), ('5', 'земли водного фонда')], default='0', max_length=50, verbose_name='Категория замель'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='desired',
            field=models.CharField(choices=[('arend', 'Аренда'), ('buy', 'Выкуп')], default='buy', max_length=50, verbose_name='Форма желаемого владения'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_api.Region', verbose_name='Район'),
        ),
    ]
