# Generated by Django 3.0.1 on 2020-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0042_auto_20200428_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='category',
            field=models.CharField(choices=[('0', 'Земли сельского назначения'), ('1', 'Земли  населенных пунктов'), ('2', 'Земли для промышленности'), ('3', 'Земли для энергетики'), ('4', 'Земли для транспорта'), ('5', 'Земли для связи'), ('6', 'Земли для радиовещания'), ('7', 'Земли для телевидения'), ('8', 'Земли для информатики'), ('9', 'Земли для обеспечения космической деятельности'), ('10', 'Земли для обороны'), ('11', 'Земли для безопасности и иного специального назначения'), ('12', 'Земли особо охраняемых территорий и объектов'), ('13', 'Земли лесного фонда'), ('14', 'Земли водного фонда')], default='0', max_length=50, verbose_name='Категория замель'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='desired',
            field=models.CharField(choices=[('arend', 'Аренда'), ('buy', 'Выкуп')], default='buy', max_length=50, verbose_name='Форма владения'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='gas',
            field=models.CharField(blank=True, max_length=500, verbose_name='Газоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='heat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Теплоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='image',
            field=models.ImageField(null=True, upload_to='greenfield', verbose_name='Фотография участка'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='power',
            field=models.CharField(blank=True, max_length=500, verbose_name='Электроснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='water',
            field=models.CharField(blank=True, max_length=500, verbose_name='Водоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='water_out',
            field=models.CharField(blank=True, max_length=500, verbose_name='Теплоотведение'),
        ),
    ]
