# Generated by Django 2.2.6 on 2020-05-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0043_auto_20200428_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='loan_time',
            field=models.CharField(blank=True, default=0, max_length=150, verbose_name='Сроки займа'),
        ),
        migrations.AlterField(
            model_name='support',
            name='money',
            field=models.CharField(blank=True, max_length=150, verbose_name='Объем меры гос.поддержки(млн.руб.)'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('direct', 'инвестиции'), ('loan_funding', 'Заемное финансирование'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=50, verbose_name='Тип поддержки'),
        ),
    ]
