# Generated by Django 3.0.4 on 2020-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0045_auto_20200521_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='territory',
            field=models.CharField(blank=True, choices=[('oez', 'ОЭЗ ППТ'), ('oezru', 'ОЭЗ Ру'), ('industrial', 'Индустриальные парки'), ('any', 'Иные площадки')], max_length=50, verbose_name='Территория участка'),
        ),
    ]
