# Generated by Django 3.0.4 on 2020-05-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0046_greenfield_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='number_territory',
            field=models.CharField(default='', max_length=100, verbose_name='Номер участка'),
        ),
    ]
