# Generated by Django 3.0.4 on 2020-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0047_auto_20200521_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenfield',
            name='privileges',
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='territory',
            field=models.CharField(choices=[('oez', 'ОЭЗ ППТ'), ('oezru', 'ОЭЗ Ру'), ('industrial', 'Индустриальный парк'), ('any', 'Иная площадка')], max_length=50, verbose_name='Территория участка'),
        ),
    ]
