# Generated by Django 3.0.4 on 2020-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0048_auto_20200524_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenfield',
            name='customs_priveleges',
            field=models.CharField(default='', max_length=100, verbose_name='Таможенные льготы'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='territory_priveleges',
            field=models.CharField(default='', max_length=100, verbose_name='Льготная стоимость земли'),
        ),
    ]
