# Generated by Django 3.0.1 on 2020-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0049_auto_20200524_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='customs_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Таможенные льготы'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='territory_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Льготная стоимость земли'),
        ),
    ]
