# Generated by Django 3.0.4 on 2020-05-28 08:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0049_auto_20200524_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='customs_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Таможенные льготы'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='territory_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Льготная стоимость земли'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('direct', 'инвестиции'), ('loan_funding', 'Заемное финансирование'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=50, verbose_name='Вид поддержки'),
        ),
    ]
