# Generated by Django 3.0.4 on 2020-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0053_auto_20200528_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Тип проекта')),
            ],
        ),
        migrations.RemoveField(
            model_name='support',
            name='type_project',
        ),
        migrations.AddField(
            model_name='support',
            name='type_project',
            field=models.ManyToManyField(blank=True, to='example_api.TypeProject'),
        ),
    ]
