# Generated by Django 3.0.4 on 2020-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0054_auto_20200528_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='type_project',
            field=models.ManyToManyField(blank=True, to='example_api.TypeProject', verbose_name='Тип проекта'),
        ),
    ]
