# Generated by Django 3.0.1 on 2020-06-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0050_auto_20200525_0712'),
        ('example_api', '0055_auto_20200529_2236'),
    ]

    operations = [
    ]
