# Generated by Django 2.2.6 on 2020-06-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0056_merge_20200602_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название документа')),
                ('url', models.CharField(default='', max_length=50, verbose_name='УРЛ')),
                ('file', models.FileField(null=True, upload_to='Documents')),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('direct', 'Прямая финансовая поддержка'), ('loan_funding', 'Заемная финансовая поддержка'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=50, verbose_name='Вид поддержки'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('time', models.DateField(verbose_name='Сроки реализации')),
                ('sum', models.IntegerField(verbose_name='Сумма инвестиций(млн.руб)')),
                ('now', models.TextField(verbose_name='Текущее состояние проекта')),
                ('image', models.ImageField(null=True, upload_to='Project', verbose_name='Фотография проекта')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_api.Industry')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
