# Generated by Django 2.2.6 on 2020-06-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0057_auto_20200615_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.AlterField(
            model_name='support',
            name='form',
            field=models.CharField(blank=True, choices=[('lawyer', 'Юр.лицо'), ('ip', 'ИП'), ('municipality', 'Муниципалитет')], default='', max_length=20, verbose_name='Категория получателя'),
        ),
        migrations.AlterField(
            model_name='support',
            name='npa',
            field=models.TextField(blank=True, default='', verbose_name='НПА устанавливающий меры'),
        ),
        migrations.AlterField(
            model_name='support',
            name='program_name',
            field=models.TextField(default='', verbose_name='Наименование гос.программы'),
        ),
        migrations.AlterField(
            model_name='support',
            name='project_name',
            field=models.TextField(blank=True, default='', verbose_name='Наименование национального проекта'),
        ),
    ]
