# Generated by Django 3.0.4 on 2020-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0057_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='УРЛ'),
        ),
    ]
