# Generated by Django 3.0.1 on 2020-06-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0058_auto_20200615_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Форма собственности')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Форма собственности',
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='time',
        ),
        migrations.AddField(
            model_name='greenfield',
            name='nalog',
            field=models.TextField(blank=True, null=True, verbose_name='Налоговые льготы'),
        ),
        migrations.AddField(
            model_name='industry',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='finish',
            field=models.IntegerField(null=True, verbose_name='Конец реализации проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.IntegerField(null=True, verbose_name='Начало реализации проекта'),
        ),
        migrations.AddField(
            model_name='support',
            name='nalog',
            field=models.TextField(blank=True, null=True, verbose_name='Налоговые льготы'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='customs_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Таможенные льготы'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание участка'),
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='form',
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='gas',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Газоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='heat',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Теплоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='power',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Электроснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='territory_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Льготная стоимость земли'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='water',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Водоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='water_out',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Водоотведение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_api.Industry', verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='support',
            name='summ',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сумма займа'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='form',
            field=models.ManyToManyField(to='example_api.PrivateForm', verbose_name='Форма владения'),
        ),
    ]
