# Generated by Django 3.0.4 on 2020-06-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0058_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('time', models.TextField(verbose_name='Сроки реализации')),
                ('sum', models.CharField(max_length=200, verbose_name='Сумма инвестиций')),
                ('now', models.TextField(verbose_name='Текущее состояние проекта')),
                ('image', models.ImageField(null=True, upload_to='Project', verbose_name='Фотография проекта')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_api.Industry')),
            ],
        ),
    ]
