# Generated by Django 3.0.1 on 2020-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0059_auto_20200618_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия, имя, отчество')),
                ('email', models.EmailField(max_length=300, verbose_name='Почта')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('image', models.ImageField(null=True, upload_to='contacts', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='support',
            name='percent',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Процентная ставка'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='desired',
            field=models.CharField(choices=[('private', 'Частная'), ('goverment', 'Государственная')], default='buy', max_length=50, verbose_name='Форма владения'),
        ),
        migrations.AlterField(
            model_name='support',
            name='organisation',
            field=models.TextField(blank=True, verbose_name='кто выдает меру поддержки'),
        ),
        migrations.AlterField(
            model_name='support',
            name='program_name',
            field=models.TextField(blank=True, default='', verbose_name='Наименование гос.программы'),
        ),
    ]
