# Generated by Django 3.0.4 on 2020-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0059_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.DateField(verbose_name='Сроки реализации'),
        ),
    ]
