# Generated by Django 3.0.4 on 2020-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0060_auto_20200613_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sum',
            field=models.IntegerField(max_length=200, verbose_name='Сумма инвестиций'),
        ),
    ]
