# Generated by Django 3.0.1 on 2020-07-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0060_auto_20200702_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
