# Generated by Django 3.0.1 on 2020-07-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0061_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='percent',
        ),
    ]
