# Generated by Django 3.0.4 on 2020-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0061_auto_20200613_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='project',
            name='sum',
            field=models.IntegerField(max_length=200, verbose_name='Сумма инвестиций(млн.руб)'),
        ),
    ]
