# Generated by Django 2.2.6 on 2020-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0062_remove_support_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия, имя, отчество')),
                ('email', models.EmailField(max_length=300, verbose_name='Почта')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('image', models.ImageField(null=True, upload_to='contacts', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='УРЛ'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='private',
            field=models.CharField(choices=[('goverment', 'государственная'), ('private', 'частная')], max_length=100, null=True, verbose_name='Вид собственности'),
        ),
        migrations.AddField(
            model_name='support',
            name='percent',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Процентная ставка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта проекта'),
        ),
        migrations.AlterField(
            model_name='support',
            name='form',
            field=models.CharField(blank=True, choices=[('lawyer', 'Юр.лицо'), ('ip', 'ИП'), ('municipality', 'Муниципалитет')], default=0, max_length=20, null=True, verbose_name='Категория получателя'),
        ),
        migrations.AlterField(
            model_name='support',
            name='npa',
            field=models.TextField(blank=True, default=0, verbose_name='НПА устанавливающий меры'),
        ),
        migrations.AlterField(
            model_name='support',
            name='organisation',
            field=models.TextField(verbose_name='кто выдает меру поддержки'),
        ),
        migrations.AlterField(
            model_name='support',
            name='program_name',
            field=models.TextField(blank=True, default=0, verbose_name='Наименование гос.программы'),
        ),
        migrations.AlterField(
            model_name='support',
            name='project_name',
            field=models.TextField(blank=True, default=0, verbose_name='Наименование национального проекта'),
        ),
    ]
