# Generated by Django 3.0.4 on 2020-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0063_auto_20200617_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time',
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Тело проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='finish',
            field=models.IntegerField(null=True, verbose_name='Конец реализации проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.IntegerField(null=True, verbose_name='Начало реализации проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма инвестиций(млн.руб)'),
        ),
    ]
