# Generated by Django 2.2.6 on 2020-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0063_auto_20200702_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='desired',
            field=models.CharField(choices=[('arend', 'Аренда'), ('buy', 'Выкуп')], default='buy', max_length=50, verbose_name='Форма владения'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('direct', 'Инвестиции'), ('loan_funding', 'Заемное финансирование'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=50, verbose_name='Вид поддержки'),
        ),
    ]
