# Generated by Django 2.2.6 on 2020-07-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0064_auto_20200702_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='help',
            field=models.BooleanField(default=False, verbose_name='Нуждается в финансировании'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='organisation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО')),
                ('organisation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Организация')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_api.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка  финансирования проекта',
                'verbose_name_plural': 'Заявки финансирования проектов',
            },
        ),
    ]
