# Generated by Django 3.0.4 on 2020-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0065_auto_20200703_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenfield',
            name='private',
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='desired',
            field=models.CharField(choices=[('goverment', 'Государственная'), ('private', 'Частная')], max_length=50, null=True, verbose_name='Вид собственности'),
        ),
    ]
