# Generated by Django 3.0.4 on 2020-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0065_auto_20200617_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Форма собственности')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Форма собственности',
            },
        ),
        migrations.AddField(
            model_name='greenfield',
            name='nalog',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Налоговые льготы'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='customs_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Таможенные льготы'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание участка'),
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='form',
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='gas',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Газоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='heat',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Теплоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='power',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Электроснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='territory_priveleges',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Льготная стоимость земли'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='water',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Водоснабжение'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='water_out',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Теплоотведение'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='form',
            field=models.ManyToManyField(to='example_api.PrivateForm', verbose_name='Форма собственности'),
        ),
    ]
