# Generated by Django 2.2.6 on 2020-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0066_auto_20200708_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('leader', 'руководство'), ('agent', 'агенство')], max_length=300, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='desired',
            field=models.CharField(choices=[('goverment', 'Государственная'), ('private', 'Частная')], max_length=50, null=True, verbose_name='Форма собственности'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='form',
            field=models.ManyToManyField(to='example_api.PrivateForm', verbose_name='Форма сделки'),
        ),
    ]
