# Generated by Django 3.0.4 on 2020-08-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0067_auto_20200804_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=5000, verbose_name='Название документа'),
        ),
    ]
