# Generated by Django 3.0.4 on 2020-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0067_auto_20200617_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='nalog',
            field=models.TextField(blank=True, null=True, verbose_name='Налоговые льготы'),
        ),
    ]
