# Generated by Django 2.2.6 on 2020-09-01 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0068_auto_20200810_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, null=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=300, null=True, verbose_name='Фармилия')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
                ('organisation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название компании')),
                ('profile', models.TextField(null=True, verbose_name='Профиль деятельности')),
                ('role', models.TextField(null=True, verbose_name='Ваша должность')),
                ('registration', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Зарегестрирован')),
                ('transfer', models.BooleanField(null=True, verbose_name='Нужен ли трансфер из города?')),
            ],
            options={
                'verbose_name': 'Cобытие',
                'verbose_name_plural': 'Событие',
            },
        ),
    ]
