# Generated by Django 3.1.4 on 2021-01-11 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0069_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenfieldTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_territory', models.CharField(default='', max_length=100, verbose_name='Номер участка')),
                ('number', models.CharField(default=0, max_length=50, verbose_name='Кадастровый номер')),
                ('image', models.ImageField(null=True, upload_to='greenfield', verbose_name='Фотография участка')),
                ('form', models.ManyToManyField(to='example_api.PrivateForm', verbose_name='Форма сделки')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_api.region', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SupportTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(blank=True, choices=[('without', 'Без ограничений'), ('park', 'индустриальные парки'), ('mono', 'моногород'), ('techno', 'технопарк'), ('oez', 'ОЭЗ ппт '), ('oezru', 'ОЭЗРУ'), ('cluster', 'Участник кластера'), ('all', 'Любая')], max_length=50, verbose_name='Территория реализации проекта')),
                ('recipient', models.CharField(choices=[('small', 'МСП'), ('innovation', 'Инновации'), ('all', 'Все'), ('municipality', 'муниципалитет'), ('industrial', 'Резиденты индустриальных парков'), ('developers', 'Разработчики ПО'), ('resident_oez', 'Резиденты ОЭЗРУ Липецк'), ('subject', 'Субъект'), ('legally', 'Юридические лица'), ('cooperatives', 'Кооперативы'), ('not_msp', 'Все кроме МСП')], max_length=150, verbose_name='Получатель')),
                ('type', models.CharField(choices=[('direct', 'Инвестиции'), ('loan_funding', 'Заемное финансирование'), ('loan', 'Налоговые льготы по налогу на займ'), ('subsidies', 'субсидии'), ('profit', 'Налоговые льготы по налогу на прибыль'), ('property', 'Налоговые льготы по налогу на имущество'), ('grant', 'Гранты'), ('rent', 'льготы по аренде'), ('garant', 'гарантии'), ('transport', 'Налоговые льготы по транспортному налогу'), ('earth', 'налоговые льготы по земельному налогу'), ('nds', 'налоговые льготы по уплате НДС'), ('customs', 'таможенные льготы'), ('infrastructure', 'Субсидии на инфраструктуру'), ('loan_profit', 'кредиты под залог создаваемого имущества')], max_length=50, verbose_name='Вид поддержки')),
                ('implementation', models.CharField(blank=True, choices=[('agreement', 'Соглашение'), ('gchp', 'ГЧП'), ('any', 'Любой')], max_length=50, verbose_name='Способ реализации проекта')),
                ('authority', models.CharField(blank=True, choices=[('uilo', 'УИиИ ЛО'), ('min', 'Минпромторг России'), ('bank', 'Уполномоченные банки'), ('fond', 'Фонд содействия инновациям'), ('rvk', 'АО "РВК"'), ('business', 'Центры "мой бизнес", Управляющие компании')], max_length=50, verbose_name='Куррирующий орган')),
                ('form', models.CharField(blank=True, choices=[('lawyer', 'Юр.лицо'), ('ip', 'ИП'), ('municipality', 'Муниципалитет')], default=0, max_length=20, null=True, verbose_name='Категория получателя')),
                ('industry', models.ManyToManyField(related_name='industry', to='example_api.Industry', verbose_name='Отрасль')),
                ('type_project', models.ManyToManyField(blank=True, to='example_api.TypeProject', verbose_name='Тип проекта')),
            ],
            options={
                'verbose_name': 'Мера поддержки',
                'verbose_name_plural': 'Меры поддержки',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SupportTranslateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=5000, verbose_name='Имя поддержки')),
                ('target', models.TextField(blank=True, default=0, verbose_name='Цели/адресаты гос.поддержки')),
                ('nalog', models.TextField(blank=True, null=True, verbose_name='Налоговые льготы')),
                ('expenses', models.TextField(blank=True, verbose_name='Затраты подлежащие возмещению')),
                ('project_name', models.TextField(blank=True, default=0, verbose_name='Наименование национального проекта')),
                ('program_name', models.TextField(blank=True, default=0, verbose_name='Наименование гос.программы')),
                ('npa', models.TextField(blank=True, default=0, verbose_name='НПА устанавливающий меры')),
                ('organisation', models.TextField(verbose_name='кто выдает меру поддержки')),
                ('condition', models.TextField(blank=True, verbose_name='Условия')),
                ('category', models.CharField(blank=True, max_length=300, verbose_name='Категория налогоплатильщика')),
                ('loan_time', models.CharField(blank=True, default=0, max_length=150, verbose_name='Сроки займа')),
                ('property_rate', models.TextField(blank=True, verbose_name='Налоговая ставка на имущество')),
                ('profit', models.TextField(blank=True, verbose_name='Налог на прибыль')),
                ('transport', models.TextField(blank=True, verbose_name='Налоговая ставка по транспортному налогу')),
                ('land', models.TextField(blank=True, verbose_name='Налоговая ставка по земельному налогу')),
                ('nds', models.TextField(blank=True, verbose_name='Налоговая ставка НДС')),
                ('money', models.CharField(blank=True, max_length=150, verbose_name='Объем меры гос.поддержки(млн.руб.)')),
                ('summ', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сумма займа')),
                ('percent', models.CharField(blank=True, max_length=200, null=True, verbose_name='Процентная ставка')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='example_api.supporttranslate')),
            ],
            options={
                'verbose_name': 'Мера поддержки Translation',
                'db_table': 'example_api_supporttranslate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsTranslateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(null=True, upload_to='News/img')),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('body', models.TextField(verbose_name='Текст')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликован')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='example_api.newstranslate')),
            ],
            options={
                'verbose_name': 'Новость Translation',
                'db_table': 'example_api_newstranslate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GreenfieldTranslateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание участка')),
                ('territory', models.CharField(choices=[('oez', 'ОЭЗ ППТ'), ('oezru', 'ОЭЗ Ру'), ('industrial', 'Индустриальный парк'), ('any', 'Иная площадка')], max_length=50, null=True, verbose_name='Территория участка')),
                ('type', models.CharField(choices=[('greenfield', 'Гринфилд'), ('brownfield', 'Браунфилд')], default=0, max_length=20, verbose_name='Тип участка')),
                ('square', models.CharField(default='', max_length=10, verbose_name='Площадь(га)')),
                ('power', models.CharField(blank=True, max_length=500, null=True, verbose_name='Электроснабжение')),
                ('water', models.CharField(blank=True, max_length=500, null=True, verbose_name='Водоснабжение')),
                ('gas', models.CharField(blank=True, max_length=500, null=True, verbose_name='Газоснабжение')),
                ('heat', models.CharField(blank=True, max_length=500, null=True, verbose_name='Теплоснабжение')),
                ('water_out', models.CharField(blank=True, max_length=500, null=True, verbose_name='Водоотведение')),
                ('danger', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=500, verbose_name='Класс опасности')),
                ('category', models.CharField(choices=[('0', 'Земли сельского назначения'), ('1', 'Земли  населенных пунктов'), ('2', 'Земли для промышленности'), ('3', 'Земли для энергетики'), ('4', 'Земли для транспорта'), ('5', 'Земли для связи'), ('6', 'Земли для радиовещания'), ('7', 'Земли для телевидения'), ('8', 'Земли для информатики'), ('9', 'Земли для обеспечения космической деятельности'), ('10', 'Земли для обороны'), ('11', 'Земли для безопасности и иного специального назначения'), ('12', 'Земли особо охраняемых территорий и объектов'), ('13', 'Земли лесного фонда'), ('14', 'Земли водного фонда')], default='0', max_length=50, verbose_name='Категория замель')),
                ('desired', models.CharField(choices=[('goverment', 'Государственная'), ('private', 'Частная')], max_length=50, null=True, verbose_name='Форма собственности')),
                ('customs_priveleges', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Таможенные льготы')),
                ('territory_priveleges', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Льготная стоимость земли')),
                ('nalog', models.TextField(blank=True, null=True, verbose_name='Налоговые льготы')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='example_api.greenfieldtranslate')),
            ],
            options={
                'verbose_name': 'Участок Translation',
                'db_table': 'example_api_greenfieldtranslate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
