# Generated by Django 3.1.4 on 2021-01-12 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0070_greenfieldtranslate_greenfieldtranslatetranslation_newstranslate_newstranslatetranslation_supporttra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslatetranslation',
            name='publish',
        ),
        migrations.AddField(
            model_name='newstranslate',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликован'),
        ),
    ]
