# Generated by Django 3.0.1 on 2021-01-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0071_auto_20210112_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greenfieldtranslate',
            options={'verbose_name': 'Земельный участок', 'verbose_name_plural': 'Земельные участки'},
        ),
        migrations.AlterModelOptions(
            name='greenfieldtranslatetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Земельный участок Translation'},
        ),
        migrations.AlterModelOptions(
            name='newstranslate',
            options={'ordering': ('-publish',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
