# Generated by Django 3.1.5 on 2021-01-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0072_auto_20210112_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslatetranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newstranslatetranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newstranslatetranslation',
            name='updated',
        ),
        migrations.AddField(
            model_name='newstranslate',
            name='image',
            field=models.ImageField(null=True, upload_to='News/img'),
        ),
        migrations.AddField(
            model_name='newstranslate',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newstranslate',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
