# Generated by Django 3.1.5 on 2021-01-19 05:54

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0073_auto_20210114_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('start', models.IntegerField(null=True, verbose_name='Начало реализации проекта')),
                ('finish', models.IntegerField(null=True, verbose_name='Конец реализации проекта')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание проекта проекта')),
                ('sum', models.IntegerField(verbose_name='Сумма инвестиций(млн.руб)')),
                ('now', models.TextField(verbose_name='Текущее состояние проекта')),
                ('image', models.ImageField(null=True, upload_to='Project', verbose_name='Фотография проекта')),
                ('help', models.BooleanField(default=False, verbose_name='Нуждается в финансировании')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example_api.industry', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
