# Generated by Django 3.1.5 on 2021-01-19 06:01

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0074_projecttranslate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttranslate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='projecttranslate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projecttranslate',
            name='now',
        ),
        migrations.RemoveField(
            model_name='projecttranslate',
            name='sum',
        ),
        migrations.CreateModel(
            name='ProjectTranslateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание проекта проекта')),
                ('now', models.TextField(verbose_name='Текущее состояние проекта')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='example_api.projecttranslate')),
            ],
            options={
                'verbose_name': 'Проект Translation',
                'db_table': 'example_api_projecttranslate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
