# Generated by Django 3.1.5 on 2021-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0075_auto_20210119_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslate',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма инвестиций(млн.руб)'),
        ),
    ]
